---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары из корзины
non-functional:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
      1. Навигация - легкость перемещения по сайту, доступность меню и путеводителей
      2. Интерфейс - удобство взаимодействия с элементами интерфейса, такими как кнопки, формы и ссылки
      3. Читабельность и доступность - четкое отображение текста, возможность увеличения шрифта, совместимость с ассистивными технологиями для людей с ограниченными возможностями
      4. Оптимизация для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика
      1. Производительность
      2. Масштабируемость
  - Сайт должен быть доступен на различных устройствах
      1. Адаптивный дизайн
      2. Удобство на сенсорных устройствах
      3. Сохранение функциональности
  - Интернационализация
  - Локализация
  - Проверка дизайна
