---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары из корзины
non-functional:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы:
    1.Навигация - легкость перемещения по сайту, доступность меню и путеводителей.
    2.Интерфейс - удобство взаимодействия с элементами интерфейса, такими как кнопки, формы и ссылки.
    3.Читабельность и доступность - четкое отображение текста, возможность увеличения шрифта, совместимость с ассистивными технологиями для людей с ограниченными возможностями.
    4.Поиск - эффективность поиска информации и товаров на сайте.
    5.Удобство оформления заказа - простой и интуитивный процесс добавления товаров в корзину и оформления заказа.
    6. Оптимизация для скорости работы - нужны конкретные цифры
  - Сайт должен быть безопасным и защищать данные пользователя:
    1. Защита от атак
    2. Аутентификация и авторизация
    3. Мониторинг и журналирование
    4. Актуализация и патчи
    5. Политику паролей и управление доступом
  - Сайт должен быть способен обрабатывать большое количество трафика:
    1. Производительность
    2. Масштабируемость
    3. Тестирование на производительность
    4. Бэкап и восстановление
    5. Оптимизация
    6. Мониторинг и автоматическое масштабирование
  - Сайт должен быть доступен на различных устройствах:
    1. Адаптивный дизайн
    2. Кросс-браузерная совместимость
    3. Доступность для людей с ограниченными возможностями
    4. Удобство на сенсорных устройствах
    5. Сохранение функциональности
  - Интернационализация
  - Локализация
